// <auto-generated />
using System;
using CriticalAlerts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CriticalAlerts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CriticalAlertsDbContext))]
    [Migration("20260830160849_Phase8PractitionerResponses")]
    partial class Phase8PractitionerResponses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<int?>("ConfirmedDraftVersion")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_draft_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DemoEscalationPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("demo_escalation_policy_version");

                    b.Property<string>("DemoNotificationPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("demo_notification_policy_version");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer")
                        .HasColumnName("draft_version");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("SimulationPatientReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("simulation_patient_reference");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UrgencyLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("urgency_label");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "OrganizationId");

                    b.HasIndex("DepartmentId", "OrganizationId");

                    b.HasIndex("SiteId", "OrganizationId");

                    b.HasIndex("OrganizationId", "State", "CreatedAtUtc");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertFieldConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AlertVersion")
                        .HasColumnType("integer")
                        .HasColumnName("alert_version");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_id");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_value");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("AlertId", "AlertVersion", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("UX_alert_field_confirmations_alert_id_alert_version_field_id");

                    b.ToTable("alert_field_confirmations", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertRecipientSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AlertVersion")
                        .HasColumnType("integer")
                        .HasColumnName("alert_version");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<string>("DirectoryRevision")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("directory_revision");

                    b.Property<DateTimeOffset?>("DirectorySourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("directory_source_updated_at_utc");

                    b.Property<string>("OnCallSnapshot")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("on_call_snapshot");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<Guid?>("PractitionerRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_role_id");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at_utc");

                    b.Property<Guid>("SelectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.HasIndex("PractitionerRoleId", "OrganizationId");

                    b.HasIndex("AlertId", "AlertVersion", "PractitionerId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("UX_alert_recipient_selection_version_practitioner_channel");

                    b.ToTable("alert_recipient_selections", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("policy_version");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_state");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OccurredAtUtc");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.ToTable("alert_state_transitions", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_category");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("OpenedState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("opened_state");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_reference");

                    b.Property<Guid>("RecipientSelectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_selection_id");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("RecipientSelectionId", "OrganizationId");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.DeliveryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeliveryAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_attempt_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SanitizedMetadata")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sanitized_metadata");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAttemptId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("delivery_events", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.EscalationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("policy_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("State", "NextDueAtUtc");

                    b.ToTable("escalation_runs", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.RecipientResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AlertVersion")
                        .HasColumnType("integer")
                        .HasColumnName("alert_version");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("response_category");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("response_type");

                    b.Property<string>("SanitizedReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sanitized_reason_code");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.HasIndex("OrganizationId", "AlertId", "AlertVersion", "PractitionerId", "Category")
                        .IsUnique()
                        .HasDatabaseName("UX_recipient_responses_practitioner_category");

                    b.ToTable("recipient_responses", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.ResponsibilityAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AlertVersion")
                        .HasColumnType("integer")
                        .HasColumnName("alert_version");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("SourceResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_response_id");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "OrganizationId");

                    b.HasIndex("OrganizationId", "SourceResponseId")
                        .IsUnique();

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.HasIndex("SourceResponseId", "OrganizationId");

                    b.HasIndex("OrganizationId", "AlertId", "AlertVersion", "PractitionerId")
                        .IsUnique();

                    b.ToTable("responsibility_assignments", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.SimulationDispatchScenarioSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scenario");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Channel")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId", "OrganizationId");

                    b.ToTable("simulation_dispatch_scenarios", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.ContactEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("SimulationLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("simulation_label");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.HasKey("Id");

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.ToTable("contact_endpoints", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.DirectorySourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stale");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SourceSystem", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("directory_source_records", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.DirectorySyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deactivated_count");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_summary");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_count");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_count");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "StartedAtUtc");

                    b.ToTable("directory_sync_runs", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.OnCallAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "OrganizationId");

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.HasIndex("SiteId", "OrganizationId");

                    b.HasIndex("OrganizationId", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("on_call_assignments", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.Practitioner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SimulationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("simulation_code");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IsActive");

                    b.HasIndex("OrganizationId", "SimulationCode")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LastName", "FirstName");

                    b.ToTable("practitioners", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.PractitionerRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "OrganizationId");

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.ToTable("practitioner_roles", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OrganizationId");

                    b.HasIndex("OrganizationId", "Provider", "Subject")
                        .IsUnique();

                    b.ToTable("external_identities", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.PractitionerUserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practitioner_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "PractitionerId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.HasIndex("PractitionerId", "OrganizationId");

                    b.HasIndex("UserId", "OrganizationId");

                    b.ToTable("practitioner_user_links", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SimulationHandle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("simulation_handle");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SimulationHandle")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("OrganizationId", "UserId", "RoleId");

                    b.HasIndex("RoleId", "OrganizationId");

                    b.HasIndex("UserId", "OrganizationId");

                    b.HasIndex("OrganizationId", "UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_user_roles_organization_id_user_id_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Organizations.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SimulationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("simulation_code");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "SimulationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_departments_organization_id_simulation_code");

                    b.HasIndex("SiteId", "OrganizationId");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_simulation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Organizations.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SimulationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("simulation_code");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "SimulationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_sites_organization_id_simulation_code");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.AlertTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Version")
                        .IsUnique();

                    b.ToTable("alert_templates", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.EscalationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("StopCondition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stop_condition");

                    b.Property<string>("TriggerCondition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_condition");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Version")
                        .IsUnique();

                    b.ToTable("escalation_policies", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.EscalationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("channels");

                    b.Property<TimeSpan>("Delay")
                        .HasColumnType("interval")
                        .HasColumnName("delay");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("RecipientSource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_source");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "OrganizationId");

                    b.HasIndex("PolicyId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("escalation_steps", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.NotificationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedChannels")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("allowed_channels");

                    b.Property<string>("GenericSmsTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generic_sms_template");

                    b.Property<string>("GenericVoiceTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generic_voice_template");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RetryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("retry_limit");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Version")
                        .IsUnique();

                    b.ToTable("notification_policies", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_type");

                    b.Property<string>("SanitizedMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sanitized_metadata");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OperationType", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_message_id");

                    b.Property<string>("Handler")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handler");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ExternalMessageId", "Handler")
                        .IsUnique();

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastErrorCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_category");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_state");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProcessingState", "NextAttemptAtUtc");

                    b.HasIndex("ProcessingState", "NextAttemptAtUtc", "LeaseExpiresAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.Alert", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Organizations.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Organizations.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CriticalAlerts.Domain.ProtectedValue", "ApprovedMessage", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("approved_message_ciphertext");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("approved_message_key_version");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("approved_message_purpose");

                            b1.HasKey("AlertId");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId");
                        });

                    b.OwnsOne("CriticalAlerts.Domain.ProtectedValue", "OriginalSource", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("original_source_ciphertext");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("original_source_key_version");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("original_source_purpose");

                            b1.HasKey("AlertId");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId");
                        });

                    b.OwnsOne("CriticalAlerts.Domain.ProtectedValue", "StructuredSuggestion", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("structured_suggestion_ciphertext");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("structured_suggestion_key_version");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("structured_suggestion_purpose");

                            b1.HasKey("AlertId");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId");
                        });

                    b.OwnsOne("CriticalAlerts.Domain.ProtectedValue", "Transcription", b1 =>
                        {
                            b1.Property<Guid>("AlertId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("transcription_ciphertext");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("transcription_key_version");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("transcription_purpose");

                            b1.HasKey("AlertId");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId");
                        });

                    b.Navigation("ApprovedMessage");

                    b.Navigation("OriginalSource");

                    b.Navigation("StructuredSuggestion");

                    b.Navigation("Transcription");
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertFieldConfirmation", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany("FieldConfirmations")
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertRecipientSelection", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany("RecipientSelections")
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.PractitionerRoleAssignment", null)
                        .WithMany()
                        .HasForeignKey("PractitionerRoleId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.AlertStateTransition", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany("StateTransitions")
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.DeliveryAttempt", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Alerts.AlertRecipientSelection", null)
                        .WithMany()
                        .HasForeignKey("RecipientSelectionId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.DeliveryEvent", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Delivery.DeliveryAttempt", null)
                        .WithMany()
                        .HasForeignKey("DeliveryAttemptId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.EscalationRun", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.RecipientResponse", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.ResponsibilityAssignment", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Delivery.RecipientResponse", null)
                        .WithMany()
                        .HasForeignKey("SourceResponseId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Delivery.SimulationDispatchScenarioSetting", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.ContactEndpoint", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CriticalAlerts.Domain.ProtectedValue", "ProtectedValue", b1 =>
                        {
                            b1.Property<Guid>("ContactEndpointId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("endpoint_ciphertext");

                            b1.Property<string>("KeyVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("endpoint_key_version");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("endpoint_purpose");

                            b1.HasKey("ContactEndpointId");

                            b1.ToTable("contact_endpoints");

                            b1.WithOwner()
                                .HasForeignKey("ContactEndpointId");
                        });

                    b.Navigation("ProtectedValue")
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.DirectorySourceRecord", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.DirectorySyncRun", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.OnCallAssignment", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Organizations.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.Practitioner", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Directory.PractitionerRoleAssignment", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.PractitionerUserLink", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Directory.Practitioner", null)
                        .WithMany()
                        .HasForeignKey("PractitionerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.Role", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.UserAccount", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Organizations.Department", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CriticalAlerts.Domain.Organizations.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Organizations.Site", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.AlertTemplate", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.EscalationPolicy", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.EscalationStep", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Policies.EscalationPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Policies.NotificationPolicy", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.AuditEvent", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.IdempotencyRecord", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.InboxMessage", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Reliability.OutboxMessage", b =>
                {
                    b.HasOne("CriticalAlerts.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CriticalAlerts.Domain.Alerts.Alert", b =>
                {
                    b.Navigation("FieldConfirmations");

                    b.Navigation("RecipientSelections");

                    b.Navigation("StateTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
