import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import * as api from "../lib/alerts";
import { RecipientSelection } from "../features/connected/recipient-selection";
import { ReviewAlert } from "../features/connected/review-alert";
vi.mock("../lib/alerts", async original => ({ ...await original<typeof api>(), getAlertDraft: vi.fn(), searchDirectory: vi.fn(), replaceAlertRecipients: vi.fn(), getAlertReview: vi.fn(), confirmAlertReview: vi.fn() }));
const push = vi.fn();
vi.mock("next/navigation", () => ({ useRouter: () => ({ push }) }));
afterEach(() => vi.clearAllMocks());
const practitioner: api.DirectoryPractitioner = { practitionerId: "sim-maya", displayName: "Dr. Maya Chen", firstName: "Maya", lastName: "Chen", specialty: "Emergency", department: "Fictional Emergency", site: "Fictional North", roleTitle: "Consultant", simulationCode: "SIM-PRAC-1", isActive: true, isStale: true, selectable: true, sourceSystem: "SIM-CSV", lastSynchronizedAtUtc: "2026-08-01T12:00:00Z", onCallTier: "Primary", onCallSourceSystem: "SIM-ROSTER", onCallLastSynchronizedAtUtc: "2026-08-01T12:00:00Z", practitionerRoleId: "sim-role", availableChannels: ["SecureMessage", "Sms"], selectionRevision: "revision-1" };
test("renders disambiguation and freshness, disables inactive selections and requires an explicit channel", async () => {
  vi.mocked(api.getAlertDraft).mockResolvedValue({ alertId: "sim-alert", draftVersion: 6, recipients: [] } as unknown as api.AlertDraft);
  vi.mocked(api.searchDirectory).mockResolvedValue([practitioner, { ...practitioner, practitionerId: "sim-inactive", simulationCode: "SIM-PRAC-2", isActive: false, selectable: false }]);
  vi.mocked(api.replaceAlertRecipients).mockResolvedValue({ draftVersion: 7 } as api.AlertDraft);
  render(<RecipientSelection alertId="sim-alert" />);
  const add = await screen.findByRole("checkbox", { name: /Select Dr. Maya Chen SIM-PRAC-1/ });
  expect(screen.getByRole("checkbox", { name: /Select Dr. Maya Chen SIM-PRAC-2/ })).toBeDisabled();
  expect(screen.getAllByText(/Fictional Emergency/).length).toBeGreaterThan(0);
  expect(screen.getAllByText(/Stale/).length).toBeGreaterThan(0);
  fireEvent.click(add);
  expect(screen.getByRole("button", { name: "Save recipients and reconfirm fields" })).toBeDisabled();
  fireEvent.change(screen.getByLabelText("Channel for Dr. Maya Chen SIM-PRAC-1"), { target: { value: "Sms" } });
  fireEvent.click(screen.getByRole("button", { name: "Save recipients and reconfirm fields" }));
  await waitFor(() => expect(push).toHaveBeenCalledWith("/alerts/sim-alert/compose"));
  expect(api.replaceAlertRecipients).toHaveBeenCalledWith("sim-alert", 6, [{ practitionerId: "sim-maya", practitionerRoleId: "sim-role", channel: "Sms", directoryRevision: "revision-1" }]);
});
const review: api.AlertReview = { alertId: "sim-alert", draftVersion: 9, state: "PendingConfirmation", simulationPatientReference: "SIM-PAT-EXACT", location: "Fictional room", urgencyLabel: "DEMO Urgent", approvedMessage: "SIMULATION: exact approved message", criticalFields: [{ alertVersion: 9, fieldId: "pulse", originalValue: "118", normalizedValue: "118", unit: "beats/min", status: "Confirmed" }], recipients: [{ ...practitioner, channel: "SecureMessage", selectedAtUtc: "2026-09-05T12:00:00Z", directorySourceUpdatedAtUtc: practitioner.lastSynchronizedAtUtc, onCallSnapshot: "Primary SIM-ROSTER", directoryRevision: "revision-1", selectionSource: "Manual" }], demoEscalationPolicyVersion: "DEMO-E1", demoNotificationPolicyVersion: "DEMO-N1" };
test("exact review prevents double click and reports queued without claiming delivery", async () => {
  vi.mocked(api.getAlertReview).mockResolvedValue(review);
  let complete!: (value: api.ConfirmResult) => void;
  vi.mocked(api.confirmAlertReview).mockReturnValue(new Promise(resolve => { complete = resolve; }));
  render(<ReviewAlert alertId="sim-alert" />);
  expect(await screen.findByText(review.approvedMessage)).toBeVisible();
  expect(screen.getByText(/DEMO-N1/)).toBeVisible();
  fireEvent.click(screen.getByLabelText(/I reviewed the exact/));
  const confirm = screen.getByRole("button", { name: "Confirm & Dispatch" });
  fireEvent.click(confirm); fireEvent.click(confirm);
  expect(confirm).toBeDisabled();
  expect(api.confirmAlertReview).toHaveBeenCalledTimes(1);
  complete({ alertId: "sim-alert", confirmedVersion: 9, state: "DispatchQueued", replayed: false });
  expect(await screen.findByText("DispatchQueued")).toBeVisible();
  expect(screen.getByRole("link", { name: "Open live status" })).toHaveAttribute("href", "/alerts/sim-alert/live");
});
test("network retry uses the same exact version and idempotency key and replay succeeds", async () => {
  vi.mocked(api.getAlertReview).mockResolvedValue(review);
  vi.mocked(api.confirmAlertReview).mockRejectedValueOnce(new TypeError("network")).mockResolvedValue({ alertId: "sim-alert", confirmedVersion: 9, state: "DispatchQueued", replayed: true });
  render(<ReviewAlert alertId="sim-alert" />);
  fireEvent.click(await screen.findByLabelText(/I reviewed the exact/));
  fireEvent.click(screen.getByRole("button", { name: "Confirm & Dispatch" }));
  expect(await screen.findByRole("alert")).toHaveTextContent(/network unavailable/);
  fireEvent.click(screen.getByRole("button", { name: "Retry same confirmation" }));
  expect(await screen.findByText("DispatchQueued")).toBeVisible();
  const calls = vi.mocked(api.confirmAlertReview).mock.calls;
  expect(calls[0]).toEqual(calls[1]);
});

test("explicit directory reload replaces stale evidence even when the draft version is unchanged", async () => {
  vi.mocked(api.getAlertDraft).mockResolvedValue({ alertId: "sim-alert", draftVersion: 6, recipients: [] } as unknown as api.AlertDraft);
  vi.mocked(api.searchDirectory).mockResolvedValueOnce([practitioner]).mockResolvedValue([{ ...practitioner, selectionRevision: "revision-2" }]);
  vi.mocked(api.replaceAlertRecipients).mockRejectedValueOnce(new api.AlertApiError(409, "directory-revision-changed", "Directory changed"));
  const discard = vi.spyOn(window, "confirm").mockReturnValue(true);
  render(<RecipientSelection alertId="sim-alert" />);
  fireEvent.click(await screen.findByRole("checkbox", { name: /Select Dr. Maya Chen SIM-PRAC-1/ }));
  fireEvent.change(screen.getByLabelText(/Channel for Dr. Maya Chen/), { target: { value: "Sms" } });
  fireEvent.click(screen.getByRole("button", { name: "Save recipients and reconfirm fields" }));
  await screen.findByRole("alert");
  fireEvent.click(screen.getByRole("button", { name: "Reload server state" }));
  await waitFor(() => expect(screen.getByRole("checkbox", { name: /Select Dr. Maya Chen SIM-PRAC-1/ })).not.toBeChecked());
  fireEvent.click(screen.getByRole("checkbox", { name: /Select Dr. Maya Chen SIM-PRAC-1/ }));
  fireEvent.change(screen.getByLabelText(/Channel for Dr. Maya Chen/), { target: { value: "Sms" } });
  fireEvent.click(screen.getByRole("button", { name: "Save recipients and reconfirm fields" }));
  expect(api.replaceAlertRecipients).toHaveBeenLastCalledWith("sim-alert", 6, [expect.objectContaining({ directoryRevision: "revision-2" })]);
  expect(discard).toHaveBeenCalledTimes(1);
  discard.mockRestore();
});
